import { Button, StatusBadge } from "@aevocado/design-system";
import { useLoaderData } from "react-router";
import type { LoaderFunctionArgs } from "react-router";
import { isAccessAllowed } from "@aevocado/app-access";
import { CapabilityNotice, PlatformPage } from "../components/platform-settings";
import { requireHubAccess } from "../lib/auth.server";
import type { HubLoaderData } from "../lib/auth.shared";
import { unexposedCapabilities } from "../lib/platform-capabilities.server";
import "../platform-settings.css";

export function meta() {
  return [{ title: "Data operations | Aevo Hub" }];
}

interface DataOperationsLoaderData {
  hub: HubLoaderData;
  importCapability: typeof unexposedCapabilities.imports;
  exportCapability: typeof unexposedCapabilities.exports;
  accessBlocked?: { state: "denied" | "entitlement"; reason: string };
}

export async function loader({ request }: LoaderFunctionArgs): Promise<DataOperationsLoaderData> {
  const hub = await requireHubAccess(request, "/data");
  const entitlementReasons = new Set(["ENTITLEMENT_REQUIRED", "ENTITLEMENT_INACTIVE", "ENTITLEMENT_EXPIRED", "ENTITLEMENT_PROJECTION_UNAVAILABLE"]);
  const reason = hub.access.reason;
  return {
    hub,
    importCapability: unexposedCapabilities.imports,
    exportCapability: unexposedCapabilities.exports,
    ...(!isAccessAllowed(hub.access) ? { accessBlocked: { state: entitlementReasons.has(reason) ? "entitlement" as const : "denied" as const, reason } } : {}),
  };
}

export default function DataOperationsRoute() {
  const data = useLoaderData() as DataOperationsLoaderData;
  if (data.accessBlocked) {
    return <PlatformPage eyebrow="Data operations" title="Import & export" description="Data operations require Core authorization and are executed by Core."><CapabilityNotice state={data.accessBlocked.state} title={data.accessBlocked.state === "entitlement" ? "Hub entitlement is blocked" : "Hub access is restricted"} description={`Core returned ${data.accessBlocked.reason}.`} code={data.accessBlocked.reason} /></PlatformPage>;
  }
  return (
    <PlatformPage eyebrow="Data operations" title="Import & export" description="Map fields from Core metadata, validate a preview, and track server-owned jobs and result files.">
      <div className="aevo-platform-section__heading"><div><span className="aevo-eyebrow">Core job workspace</span><h2>Import and export</h2><p>Hub will show a job only after Core accepts and returns it. No job history is stored locally.</p></div><StatusBadge tone="warning">Core capability unavailable</StatusBadge></div>
      <div className="aevo-platform-capability-grid">
        <section className="aevo-platform-section" aria-labelledby="import-heading">
          <div className="aevo-platform-section__heading"><div><span className="aevo-eyebrow">Inbound data</span><h2 id="import-heading">Import</h2><p>Choose a file only after Core publishes the accepted schema and field rules.</p></div></div>
          <label className="aevo-platform-file-field"><span>Source file</span><input type="file" disabled aria-describedby="import-unavailable" /></label>
          <div className="aevo-platform-placeholder-grid"><label><span>Target model</span><select disabled><option>Waiting for Core metadata</option></select></label><label><span>Field mapping</span><select disabled><option>Waiting for field definitions</option></select></label></div>
          <div id="import-unavailable"><CapabilityNotice state="unavailable" title="Import metadata and jobs unavailable" description={data.importCapability.message} code={data.importCapability.code} /></div>
          <div className="aevo-platform-job-status" role="status" aria-live="polite"><strong>Validation preview</strong><span>Unavailable until Core provides schema validation.</span><strong>Job progress and retry</strong><span>No import job has been returned by Core.</span></div>
          <Button type="button" disabled title="Core import capability is unavailable">Validate and import</Button>
        </section>
        <section className="aevo-platform-section" aria-labelledby="export-heading">
          <div className="aevo-platform-section__heading"><div><span className="aevo-eyebrow">Outbound data</span><h2 id="export-heading">Export</h2><p>Exports must be scoped and generated by Core for the full authorized result.</p></div></div>
          <div className="aevo-platform-placeholder-grid"><label><span>Export source</span><select disabled><option>Waiting for Core metadata</option></select></label><label><span>Format</span><select disabled><option>Waiting for Core metadata</option></select></label><label className="aevo-platform-placeholder-grid__wide"><span>Scope</span><select disabled><option>Full authorized result (server job required)</option></select></label></div>
          <CapabilityNotice state="unavailable" title="Scoped export jobs unavailable" description={data.exportCapability.message} code={data.exportCapability.code} />
          <div className="aevo-platform-job-status" role="status" aria-live="polite"><strong>Export job</strong><span>Unavailable; no current-page data is labeled as a full-result export.</span><strong>Download and retry</strong><span>Core has not returned a result file or retryable job status.</span></div>
          <Button type="button" disabled title="Core export capability is unavailable">Request full-result export</Button>
        </section>
      </div>
    </PlatformPage>
  );
}
